version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: crud
  web:
    image: dockerpractice
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["node", "index.js"]
networks:
  webnet: